const LANGUAGES={
  Shona:{
    config:{language:"Shona",atomic_graphemes:["ch","sh","sv","zv","ng","mb","nd","nj","ny","nz","mh","pf","ts","dz","vh"],ignore_casing:true,strip_diacritics:false,preserve_marks:[]},
    words:[
      ["amai","Mubereki wechikadzi","mother","a·mai","family"],
      ["baba","Mubereki wechirume","father","ba·ba","family"],
      ["mwana","Mwana muduku ari kumba","child","mwa·na","family"],
      ["mukoma","Mukoma wangu ari kukura","older sibling","mu·ko·ma","family"],
      ["ambuya","Ambuya vanoita sadza","grandmother","am·bu·ya","family"],
      ["sekuru","Sekuru vane ngano","grandfather / uncle","se·ku·ru","family"],
      ["tete","Tete vanofarira vana","paternal aunt","te·te","family"],
      ["mudzimai","Mudzimai wake anoimba","wife / woman","mu·dzi·mai","family"],
      ["murume","Murume wake anoshandira","husband / man","mu·ru·me","family"],
      ["mhuri","Mhuri yangu ine vanhu","family","mhu·ri","family"],
      ["muzukuru","Muzukuru wangu ane makore gumi","grandchild / niece / nephew","mu·zu·ku·ru","family"],
      ["muroora","Muroora wake anoita basa","daughter-in-law","mu·roo·ra","family"],
      ["hanzvadzi","Hanzvadzi yangu iri kuchikoro","sibling","han·zva·dzi","family"],
      ["mombe","Mombe inodya uswa","cow","mo·mbe","animals"],
      ["imbwa","Imbwa inoruma","dog","im·bwa","animals"],
      ["katsi","Katsi inobata mbeva","cat","ka·tsi","animals"],
      ["shiri","Shiri inobhururuka","bird","shi·ri","animals"],
      ["shumba","Shumba inyama yesango","lion","shum·ba","animals"],
      ["nzou","Nzou ine mhino refu","elephant","nzou","animals"],
      ["mbudzi","Mbudzi inodya mashizha","goat","mbu·dzi","animals"],
      ["huku","Huku inobereka mazai","chicken","hu·ku","animals"],
      ["mbeva","Mbeva inobva muimba","mouse / rat","mbe·va","animals"],
      ["nguruve","Nguruve inofarira matope","pig","ngu·ru·ve","animals"],
      ["tsuro","Tsuro inomhanya","rabbit / hare","tsu·ro","animals"],
      ["hove","Hove dzinogara mumvura","fish","ho·ve","animals"],
      ["gudo","Gudo rinogara pamawere","baboon","gu·do","animals"],
      ["soko","Soko rinogara mumiti","monkey","so·ko","animals"],
      ["sadza","Sadza ndicho chikafu chedu","thick maize porridge","sa·dza","food"],
      ["nyama","Nyama yemombe inonaka","meat","nya·ma","food"],
      ["muriwo","Muriwo unodya madekwana","vegetables / relish","mu·ri·wo","food"],
      ["dovi","Dovi rinoitwa nenzungu","peanut butter","do·vi","food"],
      ["chibage","Chibage chinoitwa sadza","maize cob","chi·ba·ge","food"],
      ["mazai","Mazai ehuku anochekwa","eggs","ma·zai","food"],
      ["mukaka","Mukaka unobva kumombe","milk","mu·ka·ka","food"],
      ["bota","Bota rinoitwa mangwanani","thin porridge","bo·ta","food"],
      ["nyimo","Nyimo dzinobikwa","bambara nuts","nyi·mo","food"],
      ["tsanga","Mbeu yezvirimwa","grain / seed","tsa·nga","food"],
      ["muti","Muti une mashizha","tree","mu·ti","nature"],
      ["nyika","Nyika yedu inonaka","country / land","nyi·ka","nature"],
      ["rwizi","Rwizi runoyerera","river","rwi·zi","nature"],
      ["denga","Denga rine nyeredzi","sky","de·nga","nature"],
      ["zuva","Zuva rinobuda mangwanani","sun / day","zu·va","nature"],
      ["mwedzi","Mwedzi unoonekwa usiku","moon / month","mwe·dzi","nature"],
      ["nyeredzi","Nyeredzi dzinokwira usiku","stars","nye·re·dzi","nature"],
      ["mvura","Mvura inaya kubva denga","rain / water","mvu·ra","nature"],
      ["moto","Moto unopisa zvakanyanya","fire","mo·to","nature"],
      ["guruva","Guruva rinomuka pasi","dust","gu·ru·va","nature"],
      ["jani","Jani remusango","leaf","ja·ni","nature"],
      ["dombo","Dombo guru rine simba","rock / stone","do·mbo","nature"],
      ["mhepo","Mhepo inobhururuka","wind / air","mhe·po","nature"],
      ["gomo","Gomo redu rine chando","mountain / hill","go·mo","nature"],
      ["sango","Sango rine miti mizhinji","forest / bush","sa·ngo","nature"],
      ["musha","Musha wedu uri kunyika","home village","mu·sha","places"],
      ["chikoro","Nzvimbo inodzidzirwa vana","school","chi·ko·ro","places"],
      ["nzira","Nzira inoenda kumusha","road / path","nzi·ra","places"],
      ["guta","Guta guru riri Harare","city / town","gu·ta","places"],
      ["munda","Munda une chibage","field / farm","mu·nda","places"],
      ["chitoro","Chitoro chine zvinhu zvakawanda","shop / store","chi·to·ro","places"],
      ["chipatara","Chipatara chine chiremba","hospital","chi·pa·ta·ra","places"],
      ["chechi","Chechi ine vanhu vekunamata","church","che·chi","places"],
      ["bonde","Bonde rine uswa hurefu","valley","bo·nde","places"],
      ["musoro","Musoro ndewako","head","mu·so·ro","body"],
      ["moyo","Moyo unorova nguva dzose","heart","mo·yo","body"],
      ["ruoko","Ruoko rwunobata zvinhu","hand / arm","ruo·ko","body"],
      ["gumbo","Gumbo rinofambisa munhu","leg / foot","gu·mbo","body"],
      ["nzeve","Nzeve dzinonzwa mazwi","ears","nze·ve","body"],
      ["muromo","Muromo unotaura mazwi","mouth","mu·ro·mo","body"],
      ["mhino","Mhino inanhuhwirira","nose","mhi·no","body"],
      ["tsoka","Tsoka dzinofamba pasi","feet","tso·ka","body"],
      ["chipfuva","Chipfuva chine moyo mukati","chest","chi·pfu·va","body"],
      ["bvudzi","Bvudzi riri pamusoro","hair","bvu·dzi","body"],
      ["mangwanani","Mangwanani tinosimuka","morning","ma·ngwa·na·ni","time"],
      ["masikati","Masikati zuva rinopisa","afternoon","ma·si·ka·ti","time"],
      ["usiku","Usiku tinorara","night","u·si·ku","time"],
      ["nhasi","Zuva ratiri kurarama iri zvino","today","nha·si","time"],
      ["mangwana","Mangwana tichaenda","tomorrow","ma·ngwa·na","time"],
      ["nezuro","Nezuro takaenda","yesterday","ne·zu·ro","time"],
      ["gore","Gore rino rine mvura","year","go·re","time"],
      ["svondo","Svondo tinonamata","week / Sunday","svo·ndo","time"],
      ["rudo","Rudo runobatanidza vanhu","love","ru·do","values"],
      ["unhu","Unhu ndohushamwari","ubuntu / humanity","u·nhu","values"],
      ["simba","Simba rinobva muMwari","strength","si·mba","values"],
      ["shamwari","Shamwari yangu yakanaka","friend","sha·mwa·ri","values"],
      ["rugare","Rugare runoda moyo","peace","ru·ga·re","values"],
      ["kutenda","Kutenda kunofadza","gratitude / faith","ku·te·nda","values"],
      ["ngoma","Chiridzwa chinorohwa","drum","ngo·ma","values"],
      ["mbira","Chiridzwa chine simbi","thumb piano","mbi·ra","values"],
      ["imba","Imba yedu ine makamuri","house / home","i·mba","household"],
      ["gonhi","Gonhi riri kuvhurika","door","go·nhi","household"],
      ["hwindo","Hwindo rine girimisi","window","hwi·ndo","household"],
      ["tafura","Tafura ine zvokudya","table","ta·fu·ra","household"],
      ["chigaro","Chigaro chinogara vanhu","chair / seat","chi·ga·ro","household"],
      ["mukombe","Mukombe une mvura","cup","mu·ko·mbe","household"],
      ["jiko","Jiko rinopisa nemoto","stove / fireplace","ji·ko","household"],
      ["ndiro","Ndiro ine sadza","plate / dish","ndi·ro","household"],
      ["mubhedha","Mubhedha une mirinda","bed","mu·bhe·dha","household"],
      ["piri","Piri ndiwo nhamba yechipiri","two","pi·ri","numbers"],
      ["tatu","Tatu ndiwo nhamba yechitatu","three","ta·tu","numbers"],
      ["shanu","Shanu ndiwo nhamba yechishanu","five","sha·nu","numbers"],
      ["tanhatu","Tanhatu ndiwo nhamba yechitanhatu","six","ta·nha·tu","numbers"],
      ["nomwe","Nomwe ndiwo nhamba yechinomwe","seven","no·mwe","numbers"],
      ["sere","Sere ndiwo nhamba yechisere","eight","se·re","numbers"],
      ["gumi","Gumi ndiwo nhamba yechigumi","ten","gu·mi","numbers"],
      ["zana","Zana ndiwo nhamba zana","hundred","za·na","numbers"],
      ["babamukuru","Mukoma wababa vako","father's older brother / uncle","ba·ba·mu·ku·ru","family"],
      ["babamunini","Munin'ina wababa vako","father's younger brother / uncle","ba·ba·mu·ni·ni","family"],
      ["maiguru","Mukadzi wababamukuru","aunt / co-wife (senior)","ma·i·gu·ru","family"],
      ["mainini","Munin'ina waamai","aunt / mother's younger sister","ma·i·ni·ni","family"],
      ["mukwasha","Murume wemwanasikana","son-in-law","mu·kwa·sha","family"],
      ["mwanasikana","Mwana wechikadzi","daughter","mwa·na·si·ka·na","family"],
      ["mwanakomana","Mwana wechirume","son","mwa·na·ko·ma·na","family"],
      ["mhuru","Mwana wemombe","calf","mhu·ru","animals"],
      ["bhiza","Mhuka inotakura vanhu","horse","bhi·za","animals"],
      ["dhongi","Mhuka inotakura mitoro","donkey","dho·ngi","animals"],
      ["nyoka","Inokambaira pasi","snake","nyo·ka","animals"],
      ["datya","Rinosvetuka mumvura","frog","da·tya","animals"],
      ["nyuchi","Inogadzira uchi","bee","nyu·chi","animals"],
      ["nhunzi","Inomhara pazvokudya","fly","nhu·nzi","animals"],
      ["gonzo","Mbeva huru yemumba","rat","go·nzo","animals"],
      ["ngwena","Mhuka huru yemurwizi","crocodile","ngwe·na","animals"],
      ["mhembwe","Mhuka diki yesango","duiker / antelope","mhe·mbwe","animals"],
      ["nzungu","Inodyiwa, inoita dovi","peanut / groundnut","nzu·ngu","food"],
      ["mupunga","Zvokudya zvichena zvinobikwa","rice","mu·pu·nga","food"],
      ["nyemba","Tsanga dzemumunda","cowpeas / beans","nye·mba","food"],
      ["manhanga","Muriwo unobva kumudzimba","pumpkin","ma·nha·nga","food"],
      ["muboora","Mashizha emanhanga anodyiwa","pumpkin leaves","mu·bo·o·ra","food"],
      ["nyevhe","Muriwo wesango unodyiwa","spider plant (relish)","nye·vhe","food"],
      ["mufushwa","Muriwo wakaomeswa","dried vegetables","mu·fu·shwa","food"],
      ["maputi","Chibage chakakangwa","roasted maize","ma·pu·ti","food"],
      ["mvuu","Mhuka huru inogara mumvura","hippopotamus","mvu·u","animals"],
      ["munyu","Unoisa kuti zvokudya zvinake","salt","mu·nyu","food"],
      ["uchi","Zvinotapira zvinobva kunyuchi","honey","u·chi","food"],
      ["mafuta","Anoshandiswa kubika","oil / fat","ma·fu·ta","food"],
      ["chingwa","Chinodyiwa mangwanani","bread","chi·ngwa","food"],
      ["doro","Hwahwa hwechivanhu","beer","do·ro","food"],
      ["rurimi","Runoshandiswa kuravira","tongue","ru·ri·mi","body"],
      ["ziso","Rinoshandiswa kuona","eye","zi·so","body"],
      ["chiuno","Pakati pemuviri","waist","chi·u·no","body"],
      ["bendekete","Pamusoro peruoko","shoulder","be·nde·ke·te","body"],
      ["chibvi","Panopinda gumbo","knee","chi·bvi","body"],
      ["munwe","Chikamu cheruoko","finger","mu·nwe","body"],
      ["ropa","Zvitsvuku zviri mumuviri","blood","ro·pa","body"],
      ["ganda","Rinofukidza muviri","skin","ga·nda","body"],
      ["chitubu","Panobuda mvura yepasi","spring / fountain","chi·tu·bu","nature"],
      ["dziva","Mvura yakamira pasango","pool / pond","dzi·va","nature"],
      ["jecha","Zvidiki zvepasi pedyo nerwizi","sand","je·cha","nature"],
      ["ivhu","Pasi panodyarwa zvirimwa","soil / earth","i·vhu","nature"],
      ["chando","Kutonhora kwakanyanya","cold / frost","cha·ndo","nature"],
      ["mhute","Inofukidza pasango mangwanani","mist / fog","mhu·te","nature"],
      ["dutu","Mhepo ine simba","storm","du·tu","nature"],
      ["bani","Nzvimbo yakati sandara","plain / open field","ba·ni","nature"],
      ["chikomo","Gomo diki","hill","chi·ko·mo","nature"],
      ["dunhu","Chikamu chenyika","district / region","du·nhu","places"],
      ["musika","Panotengeswa zvinhu","market","mu·si·ka","places"],
      ["mabhuku","Zvinoverengwa kuchikoro","books","ma·bhu·ku","household"],
      ["poto","Inoshandiswa kubika","pot","po·to","household"],
      ["hari","Mudziyo wevhu wokubika","clay pot","ha·ri","household"],
      ["banga","Chinoshandiswa kucheka","knife","ba·nga","household"],
      ["demo","Chinoshandiswa kutema huni","axe","de·mo","household"],
      ["badza","Chinoshandiswa kurima","hoe","ba·dza","household"],
      ["rusero","Chinoshandiswa kuzunza upfu","winnowing basket","ru·se·ro","household"],
      ["tswanda","Dengu rokutakura zvinhu","basket","tswa·nda","household"],
      ["gumbeze","Chokufuga pakurara","blanket","gu·mbe·ze","household"],
      ["ina","Nhamba inotevera tatu","four","i·na","numbers"],
      ["chokwadi","Chinhu chisina manyepo","truth","cho·kwa·di","values"],
      ["runyararo","Kusava nehondo","peace","ru·nya·ra·ro","values"],
      ["tsitsi","Kunzwira mumwe urombo","mercy / compassion","tsi·tsi","values"],
      ["ushingi","Kuva nesimba remwoyo","courage / bravery","u·shi·ngi","values"],
      ["nguva","Zvinoyerwa newachi","time","ngu·va","time"]
    ]
  },
  Swahili:{
    config:{language:"Swahili",atomic_graphemes:["ng'","ch","sh","gh","kh","th","dh","ng","ny","mb","nd"],ignore_casing:true,strip_diacritics:true,preserve_marks:["'"]},
    words:[
      ["mama","Mama yangu anapenda familia","mother","ma·ma","family"],
      ["baba","Baba yangu anafanya kazi","father","ba·ba","family"],
      ["mtoto","Mtoto mdogo anacheza","child","mto·to","family"],
      ["kaka","Kaka yangu ni mkubwa","older brother","ka·ka","family"],
      ["dada","Dada yangu ni mzuri","older sister","da·da","family"],
      ["bibi","Bibi yangu ana umri mkubwa","grandmother","bi·bi","family"],
      ["babu","Babu yangu ana nguvu","grandfather","ba·bu","family"],
      ["shangazi","Shangazi yangu ni mpole","paternal aunt","sha·nga·zi","family"],
      ["mjomba","Mjomba wangu ni mrefu","maternal uncle","mjo·mba","family"],
      ["mke","Mke wake ni mzuri sana","wife","mke","family"],
      ["mume","Mume wake anafanya kazi","husband","mu·me","family"],
      ["ndugu","Ndugu yangu yupo hapa","sibling / relative","ndu·gu","family"],
      ["mjukuu","Mjukuu wangu ni mdogo","grandchild","mju·kuu","family"],
      ["ng'ombe","Ng'ombe wangu ana nguvu","cow","ng'·o·mbe","animals"],
      ["mbwa","Mbwa wangu ni mzuri","dog","mbwa","animals"],
      ["paka","Paka anakimbia haraka","cat","pa·ka","animals"],
      ["ndege","Ndege anaruka angani","bird","nde·ge","animals"],
      ["simba","Simba ni mfalme wa msitu","lion","si·mba","animals"],
      ["tembo","Tembo ana mkonga mrefu","elephant","te·mbo","animals"],
      ["mbuzi","Mbuzi anakula majani","goat","mbu·zi","animals"],
      ["kuku","Kuku anaweza kutaga mayai","chicken","ku·ku","animals"],
      ["panya","Panya anapenda chakula","rat / mouse","pa·nya","animals"],
      ["nguruwe","Nguruwe anapenda matope","pig","ngu·ru·we","animals"],
      ["sungura","Sungura anakimbia upesi","rabbit / hare","su·ngu·ra","animals"],
      ["samaki","Samaki anaishi majini","fish","sa·ma·ki","animals"],
      ["nyoka","Nyoka anatambaa ardhini","snake","nyo·ka","animals"],
      ["farasi","Farasi anakimbia kwa kasi","horse","fa·ra·si","animals"],
      ["kondoo","Kondoo ana manyoya mazuri","sheep","ko·ndoo","animals"],
      ["chakula","Chakula hiki ni kitamu","food","cha·ku·la","food"],
      ["nyama","Nyama ya ng'ombe ni nzuri","meat","nya·ma","food"],
      ["ugali","Ugali ni chakula cha Afrika","stiff porridge","u·ga·li","food"],
      ["wali","Wali na mchuzi ni tamu","cooked rice","wa·li","food"],
      ["mboga","Mboga za majani ni muhimu","vegetables","mbo·ga","food"],
      ["mahindi","Mahindi yanakua shambani","corn / maize","ma·hi·ndi","food"],
      ["mayai","Mayai ya kuku ni mazuri","eggs","ma·ya·i","food"],
      ["maziwa","Maziwa ya ng'ombe ni mazuri","milk","ma·zi·wa","food"],
      ["chai","Chai ya asubuhi ni tamu","tea","chai","food"],
      ["mkate","Mkate na siagi ni tamu","bread","mka·te","food"],
      ["sukari","Sukari inatia utamu","sugar","su·ka·ri","food"],
      ["mchuzi","Mchuzi wa nyama unawaka","sauce / stew","mchu·zi","food"],
      ["ndizi","Ndizi ni tamu sana","banana","ndi·zi","food"],
      ["embe","Embe ni tamu wakati wa kiangazi","mango","e·mbe","food"],
      ["mchele","Mchele unapikwa na maji","uncooked rice","mche·le","food"],
      ["mti","Mti huu una matunda","tree","mti","nature"],
      ["nchi","Nchi yetu ni nzuri sana","country / land","nchi","nature"],
      ["mlima","Mlima mrefu una theluji","mountain","mli·ma","nature"],
      ["mto","Mto unatiririka","river","mto","nature"],
      ["jua","Jua linachomoza asubuhi","sun","ju·a","nature"],
      ["mwezi","Mwezi unaonekana usiku","moon / month","mwe·zi","nature"],
      ["nyota","Nyota zinaangaza usiku","stars","nyo·ta","nature"],
      ["mvua","Mvua inanyesha siku ya leo","rain","mvu·a","nature"],
      ["moto","Moto unawaka jikoni","fire","mo·to","nature"],
      ["upepo","Upepo unavuma leo","wind","u·pe·po","nature"],
      ["bahari","Bahari ina maji mengi","sea / ocean","ba·ha·ri","nature"],
      ["msitu","Msitu una miti mingi","forest","msi·tu","nature"],
      ["ziwa","Ziwa lina maji baridi","lake","zi·wa","nature"],
      ["mbingu","Mbingu zina mawingu","sky / heavens","mbi·ngu","nature"],
      ["ardhi","Ardhi hii ni nzuri","earth / ground","a·rdhi","nature"],
      ["shule","Mahali wanafunzi husoma","school","shu·le","places"],
      ["nyumba","Mahali pa kuishi","house / home","nyu·mba","places"],
      ["mji","Mji mkubwa una watu wengi","city / town","mji","places"],
      ["kijiji","Kijiji kidogo kina amani","village","ki·ji·ji","places"],
      ["duka","Duka hili lina bidhaa nyingi","shop / store","du·ka","places"],
      ["hospitali","Hospitali ina madaktari wengi","hospital","ho·spi·ta·li","places"],
      ["kanisa","Kanisa lina waumini wengi","church","ka·ni·sa","places"],
      ["shamba","Mahali pa kulima","farm / field","sha·mba","places"],
      ["barabara","Barabara hii ni ndefu","road / street","ba·ra·ba·ra","places"],
      ["soko","Soko lina bidhaa za kila aina","market","so·ko","places"],
      ["bandari","Bandari ina meli nyingi","port / harbor","ba·nda·ri","places"],
      ["msikiti","Msikiti una waumini wengi","mosque","msi·ki·ti","places"],
      ["kichwa","Kichwa changu kinauma","head","ki·chwa","body"],
      ["moyo","Moyo wangu unapiga nguvu","heart","mo·yo","body"],
      ["mkono","Mkono wangu una nguvu","hand / arm","mko·no","body"],
      ["mguu","Mguu wangu unauma leo","leg / foot","mguu","body"],
      ["macho","Macho yangu yanaona vizuri","eyes","ma·cho","body"],
      ["masikio","Masikio yangu yanasikia","ears","ma·si·ki·o","body"],
      ["mdomo","Mdomo wangu unasema","mouth","mdo·mo","body"],
      ["pua","Pua yangu inanuka harufu","nose","pu·a","body"],
      ["tumbo","Tumbo langu linauma","stomach","tu·mbo","body"],
      ["uso","Uso wake ni mzuri","face","u·so","body"],
      ["meno","Meno yangu ni meupe","teeth","me·no","body"],
      ["bega","Bega langu lina mzigo","shoulder","be·ga","body"],
      ["asubuhi","Asubuhi tunaamka mapema","morning","a·su·bu·hi","time"],
      ["mchana","Mchana jua linachoma","midday / afternoon","mcha·na","time"],
      ["jioni","Jioni tunakaa pamoja","evening","jio·ni","time"],
      ["usiku","Usiku tunalala","night","u·si·ku","time"],
      ["leo","Leo ni siku nzuri","today","le·o","time"],
      ["kesho","Kesho tutaenda sokoni","tomorrow","ke·sho","time"],
      ["jana","Jana tulikwenda shuleni","yesterday","ja·na","time"],
      ["mwaka","Mwaka huu una furaha","year","mwa·ka","time"],
      ["wiki","Wiki hii ina siku saba","week","wi·ki","time"],
      ["siku","Siku ya leo ni nzuri","day","si·ku","time"],
      ["saa","Saa ngapi sasa hivi?","hour / watch / time","saa","time"],
      ["upendo","Upendo ni zawadi ya Mungu","love","u·pe·ndo","values"],
      ["heshima","Heshima inastahili kutolewa","respect","he·shi·ma","values"],
      ["utu","Utu ndio msingi wa maisha","ubuntu / humanity","u·tu","values"],
      ["amani","Amani inahitajika kila mahali","peace","a·ma·ni","values"],
      ["nguvu","Nguvu zinatoka kwa Mungu","strength / power","ngu·vu","values"],
      ["furaha","Furaha inafanya moyo upige","joy / happiness","fu·ra·ha","values"],
      ["rafiki","Rafiki mwema ni hazina","friend","ra·fi·ki","values"],
      ["imani","Imani ni nguvu ya roho","faith / belief","i·ma·ni","values"],
      ["umoja","Umoja ni nguvu kubwa","unity","u·mo·ja","values"],
      ["huruma","Huruma inaonyesha upole","compassion / mercy","hu·ru·ma","values"],
      ["dhahabu","Madini ya thamani","gold","dha·ha·bu","values"],
      ["ghali","Chenye bei kubwa","expensive","gha·li","values"],
      ["mlango","Mlango unafunguka asubuhi","door","mla·ngo","household"],
      ["dirisha","Dirisha linaingiza mwanga","window","di·ri·sha","household"],
      ["kitanda","Kitanda changu ni laini","bed","ki·ta·nda","household"],
      ["meza","Meza ina vitabu vingi","table","me·za","household"],
      ["kiti","Kiti kizuri kina starehe","chair / seat","ki·ti","household"],
      ["sufuria","Sufuria inatumika kupikia","cooking pot","su·fu·ria","household"],
      ["kikombe","Kikombe cha chai ni kidogo","cup","ki·ko·mbe","household"],
      ["jiko","Jiko linawaka kwa moto","stove / cooker","ji·ko","household"],
      ["sahani","Sahani ina chakula","plate / dish","sa·ha·ni","household"],
      ["mkeka","Mkeka unalazwa chini","mat / rug","mke·ka","household"],
      ["mbili","Mbili ni nambari ya pili","two","mbi·li","numbers"],
      ["tatu","Tatu ni nambari ya tatu","three","ta·tu","numbers"],
      ["tano","Tano ni nambari ya tano","five","ta·no","numbers"],
      ["sita","Sita ni nambari ya sita","six","si·ta","numbers"],
      ["saba","Saba ni nambari ya saba","seven","sa·ba","numbers"],
      ["nane","Nane ni nambari ya nane","eight","na·ne","numbers"],
      ["tisa","Tisa ni nambari ya tisa","nine","ti·sa","numbers"],
      ["kumi","Kumi ni nambari ya kumi","ten","ku·mi","numbers"],
      ["ishirini","Ishirini ni mara mbili ya kumi","twenty","i·shi·ri·ni","numbers"],
      ["thelathini","Thelathini ni mara tatu ya kumi","thirty","the·la·thi·ni","numbers"],
      ["elfu","Elfu ni nambari kubwa sana","thousand","e·lfu","numbers"],
      ["mtu","Binadamu mmoja yeyote","person","m·tu","family"],
      ["watu","Binadamu wengi kwa pamoja","people","wa·tu","family"],
      ["binti","Mtoto wa kike wa mtu","daughter","bi·nti","family"],
      ["mvulana","Mtoto wa kiume","boy","mvu·la·na","family"],
      ["msichana","Mtoto wa kike","girl","msi·cha·na","family"],
      ["mzee","Mtu aliyezeeka sana","elder","mze·e","family"],
      ["jirani","Mtu anayeishi karibu nawe","neighbor","ji·ra·ni","family"],
      ["mwalimu","Mtu anayefundisha shuleni","teacher","mwa·li·mu","family"],
      ["mgeni","Mtu anayetembelea","guest / stranger","mge·ni","family"],
      ["chui","Mnyama mwenye madoadoa","leopard","chu·i","animals"],
      ["twiga","Mnyama mwenye shingo ndefu","giraffe","twi·ga","animals"],
      ["kiboko","Mnyama mkubwa wa majini","hippopotamus","ki·bo·ko","animals"],
      ["kima","Aina ya nyani mdogo","monkey","ki·ma","animals"],
      ["nyani","Mnyama anayepanda miti","baboon","nya·ni","animals"],
      ["popo","Mnyama anayeruka usiku","bat","po·po","animals"],
      ["mamba","Mnyama hatari wa mtoni","crocodile","ma·mba","animals"],
      ["nyuki","Mdudu anayetengeneza asali","bee","nyu·ki","animals"],
      ["buibui","Mdudu anayefuma utando","spider","bui·bui","animals"],
      ["kobe","Mnyama mwenye gamba gumu","tortoise","ko·be","animals"],
      ["punda","Mnyama anayebeba mizigo","donkey","pu·nda","animals"],
      ["fisi","Mnyama anayecheka usiku","hyena","fi·si","animals"],
      ["asali","Kitu kitamu kutoka kwa nyuki","honey","a·sa·li","food"],
      ["chumvi","Kitu cha kuongeza ladha","salt","chu·mvi","food"],
      ["pilipili","Kiungo chenye ukali","pepper / chili","pi·li·pi·li","food"],
      ["mafuta","Kitu cha kupikia chenye unyevu","oil / fat","ma·fu·ta","food"],
      ["unga","Mahindi yaliyosagwa","flour","u·nga","food"],
      ["matunda","Vyakula vitamu vya miti","fruits","ma·tu·nda","food"],
      ["nazi","Tunda la mnazi","coconut","na·zi","food"],
      ["chungwa","Tunda la rangi ya machungwa","orange","chu·ngwa","food"],
      ["nanasi","Tunda lenye taji","pineapple","na·na·si","food"],
      ["viazi","Mboga inayootea ardhini","potatoes","vi·a·zi","food"],
      ["maua","Vitu vizuri vya mimea","flowers","ma·u·a","nature"],
      ["jiwe","Kitu kigumu cha ardhini","stone","ji·we","nature"],
      ["mchanga","Vumbi laini la pwani","sand","mcha·nga","nature"],
      ["wingu","Kitu cheupe angani","cloud","wi·ngu","nature"],
      ["theluji","Maji yaliyoganda meupe","snow","the·lu·ji","nature"],
      ["umeme","Mwanga wa radi angani","lightning","u·me·me","nature"],
      ["majani","Sehemu za kijani za mti","leaves / grass","ma·ja·ni","nature"],
      ["mwamba","Jiwe kubwa gumu","rock","mwa·mba","nature"],
      ["jangwa","Eneo kavu lenye mchanga","desert","ja·ngwa","nature"],
      ["kisima","Shimo la kupata maji","well","ki·si·ma","nature"],
      ["mfereji","Njia ya kupitisha maji","canal / ditch","mfe·re·ji","nature"],
      ["chumba","Sehemu moja ndani ya nyumba","room","chu·mba","places"],
      ["choo","Mahali pa kujisaidia","toilet","cho·o","places"],
      ["jiji","Mji mkubwa sana","city","ji·ji","places"],
      ["uwanja","Eneo wazi la michezo","field / ground","uwa·nja","places"],
      ["daraja","Njia ya kuvuka mto","bridge","da·ra·ja","places"],
      ["kiwanda","Mahali pa kutengeneza bidhaa","factory","ki·wa·nda","places"],
      ["ofisi","Mahali pa kufanyia kazi","office","o·fi·si","places"],
      ["gereza","Mahali pa kufungia wahalifu","prison","ge·re·za","places"],
      ["kidole","Sehemu ndogo ya mkono","finger","ki·do·le","body"],
      ["nywele","Vitu vinavyoota kichwani","hair","nywe·le","body"],
      ["ulimi","Kiungo cha kuonja kinywani","tongue","u·li·mi","body"],
      ["shingo","Sehemu kati ya kichwa na mwili","neck","shi·ngo","body"],
      ["damu","Maji mekundu mwilini","blood","da·mu","body"],
      ["mfupa","Kitu kigumu ndani ya mwili","bone","mfu·pa","body"],
      ["ngozi","Kifuniko cha nje cha mwili","skin","ngo·zi","body"],
      ["kidevu","Sehemu ya chini ya uso","chin","ki·de·vu","body"],
      ["dakika","Sehemu ndogo ya saa","minute","da·ki·ka","time"],
      ["sasa","Wakati huu wa hivi karibuni","now","sa·sa","time"],
      ["zamani","Wakati uliopita kitambo","past / old times","za·ma·ni","time"],
      ["ukweli","Kitu kisicho na uongo","truth","u·kwe·li","values"],
      ["haki","Kitu cha sawa na adili","justice / right","ha·ki","values"],
      ["uhuru","Hali ya kutokuwa mtumwa","freedom","u·hu·ru","values"],
      ["uvumilivu","Hali ya kustahimili","patience","u·vu·mi·li·vu","values"],
      ["ukarimu","Hali ya kupenda kutoa","generosity","u·ka·ri·mu","values"],
      ["bidii","Kufanya kazi kwa juhudi","diligence","bi·di·i","values"],
      ["kioo","Kitu cha kujionea sura","mirror / glass","ki·o·o","household"],
      ["ufagio","Kitu cha kufagia sakafu","broom","u·fa·gi·o","household"],
      ["sabuni","Kitu cha kuoshea uchafu","soap","sa·bu·ni","household"],
      ["taa","Kitu cha kutoa mwanga","lamp / light","ta·a","household"],
      ["kisu","Kitu cha kukatia","knife","ki·su","household"],
      ["uma","Kitu cha kulia chakula","fork","u·ma","household"],
      ["ndoo","Chombo cha kubebea maji","bucket","ndo·o","household"],
      ["moja","Namba ya kwanza kabisa","one","mo·ja","numbers"],
      ["nne","Namba kati ya tatu na tano","four","nne","numbers"],
      ["mia","Makumi kumi kwa pamoja","hundred","mi·a","numbers"],
      ["milioni","Idadi kubwa sana ya elfu","million","mi·li·o·ni","numbers"]
    ]
  },
  Zulu:{
    config:{language:"Zulu",atomic_graphemes:["ngc","ngq","ngx","nkc","nkq","nkx","ntsh","tsh","dlw","shw","bh","ch","dl","gc","gq","gx","hh","hl","kh","kl","ph","sh","th","ts","ny","ng","nc","nq","nx","c","q","x"],ignore_casing:true,strip_diacritics:false,preserve_marks:[]},
    beta:true,
    words:[
      ["umama","umzali wesifazane","mother","u·ma·ma","family"],
      ["ubaba","umzali wesilisa","father","u·ba·ba","family"],
      ["umfana","umntwana wesilisa","boy","um·fa·na","family"],
      ["intombazane","umntwana wesifazane","girl","i·nto·mba·za·ne","family"],
      ["ingane","umntwana omncane","child","i·nga·ne","family"],
      ["udadewethu","Udade womndeni wakwethu","my sister","u·da·de·we·thu","family"],
      ["umfowethu","Umfana womndeni wakwethu","my brother","um·fo·we·thu","family"],
      ["ugogo","umama kamama","grandmother","u·go·go","family"],
      ["umkhulu","ubaba kababa","grandfather","um·khu·lu","family"],
      ["umngane","umuntu omthandayo","friend","um·nga·ne","family"],
      ["inja","isilwane esikhonkothayo","dog","i·nja","animals"],
      ["ikati","isilwane esincane sasekhaya","cat","i·ka·ti","animals"],
      ["inkomo","isilwane esikhulu sasepulazini","cow","i·nko·mo","animals"],
      ["imbuzi","isilwane esinezimpondo","goat","i·mbu·zi","animals"],
      ["ingulube","isilwane esikhuluphele","pig","i·ngu·lu·be","animals"],
      ["inkukhu","inyoni ezalela amaqanda","chicken","i·nku·khu","animals"],
      ["ihhashi","isilwane esigitshelwayo","horse","i·hha·shi","animals"],
      ["ingwe","isilwane esinamabala","leopard","i·ngwe","animals"],
      ["ibhubesi","inkosi yezilwane","lion","i·bhu·be·si","animals"],
      ["indlovu","isilwane esikhulu kunazo zonke","elephant","i·ndlo·vu","animals"],
      ["inyoka","isilwane esihuquzelayo","snake","i·nyo·ka","animals"],
      ["inyoni","isilwane esindizayo","bird","i·nyo·ni","animals"],
      ["intuthwane","isinambuzane esincane","ant","i·ntu·thwa·ne","animals"],
      ["ukudla","into esiyidlayo","food","u·ku·dla","food"],
      ["isinkwa","ukudla okubhakiwe","bread","i·si·nkwa","food"],
      ["ubisi","okuphuma enkomeni","milk","u·bi·si","food"],
      ["inyama","ukudla okuvela ezilwaneni","meat","i·nya·ma","food"],
      ["amazambane","ukudla okumbiwa emhlabathini","potatoes","a·ma·za·mba·ne","food"],
      ["itiye","isiphuzo esishisayo","tea","i·ti·ye","food"],
      ["ilanga","liyakhanya emini","sun","i·la·nga","nature"],
      ["inyanga","ikhanya ebusuku","moon","i·nya·nga","nature"],
      ["amanzi","aphuzwayo nawagelezayo","water","a·ma·nzi","nature"],
      ["umoya","esiwuphefumulayo","wind / spirit","u·mo·ya","nature"],
      ["imvula","amanzi awa esibhakabhakeni","rain","i·mvu·la","nature"],
      ["umlilo","into eshisayo evuthayo","fire","u·mli·lo","nature"],
      ["intaba","indawo ephakeme emhlabeni","mountain","i·nta·ba","nature"],
      ["umfula","amanzi agelezayo","river","u·mfu·la","nature"],
      ["isihlahla","simila phansi sinamagatsha","tree","i·si·hla·hla","nature"],
      ["izulu","esibhakabhaka esiphezulu","sky","i·zu·lu","nature"],
      ["ikhaya","indawo esihlala kuyo","home","i·kha·ya","places"],
      ["isikole","indawo yokufunda","school","i·si·ko·le","places"],
      ["idolobha","indawo enezitolo eziningi","town","i·do·lo·bha","places"],
      ["ikhanda","ingxenye ephezulu yomzimba","head","i·kha·nda","body"],
      ["amehlo","esibona ngawo","eyes","a·me·hlo","body"],
      ["indlebe","esizwa ngayo","ear","i·ndle·be","body"],
      ["umlomo","esikhuluma ngawo","mouth","u·mlo·mo","body"],
      ["isandla","esibamba ngaso","hand","i·sa·ndla","body"],
      ["unyawo","esihamba ngalo","foot","u·nya·wo","body"],
      ["inhliziyo","eshaya esifubeni","heart","i·nhli·zi·yo","body"],
      ["usuku","amahora angamashumi amabili nane","day","u·su·ku","time"],
      ["ubusuku","isikhathi sobumnyama","night","u·bu·su·ku","time"],
      ["namuhla","usuku esikulo manje","today","na·mu·hla","time"],
      ["izolo","usuku oludlule","yesterday","i·zo·lo","time"],
      ["uthando","umuzwa wokuthanda","love","u·tha·ndo","values"],
      ["ukuthula","ukungabi nempi","peace","u·ku·thu·la","values"],
      ["iqiniso","okuyikho hhayi amanga","truth","i·qi·ni·so","values"],
      ["umnyango","esingena ngawo endlini","door","u·mnya·ngo","household"],
      ["itafula","sidlela kulo","table","i·ta·fu·la","household"],
      ["umbhede","esilala kuwo","bed","u·mbhe·de","household"]
    ]
  }
};

/* ── Expanded word sets (appended & de-duplicated) — 200+ per language for variance ── */
const SHONA_MORE=[
  ["sahwira","Shamwari yepedyo yemhuri","close family friend","sa·hwi·ra","family"],
  ["babamukuru","Mukoma wababa vako","father's elder brother","ba·ba·mu·ku·ru","family"],
  ["babamunini","Munin'ina wababa vako","father's younger brother","ba·ba·mu·ni·ni","family"],
  ["mainini","Munin'ina waamai vako","mother's younger sister","ma·i·ni·ni","family"],
  ["maiguru","Mukoma waamai vako","mother's elder sister","ma·i·gu·ru","family"],
  ["vatete","Hanzvadzi yababa vako","father's sister / aunt","va·te·te","family"],
  ["mukwasha","Murume womwana wechikadzi","son-in-law","mu·kwa·sha","family"],
  ["mwanakomana","Mwana wechirume","son","mwa·na·ko·ma·na","family"],
  ["mwanasikana","Mwana wechikadzi","daughter","mwa·na·si·ka·na","family"],
  ["tezvara","Baba vomukadzi wako","father-in-law","te·zva·ra","family"],
  ["ngwena","Mhuka inogara mumvura ine meno","crocodile","ngwe·na","animals"],
  ["mvuu","Mhuka huru inogara murwizi","hippopotamus","mvu·u","animals"],
  ["twiza","Mhuka ine mutsipa murefu","giraffe","twi·za","animals"],
  ["nyati","Mhuka huru ine nyanga","buffalo","nya·ti","animals"],
  ["mhembwe","Mhuka diki inomhanya musango","duiker / antelope","mhe·mbwe","animals"],
  ["mhara","Mhuka inomhanya musango","impala","mha·ra","animals"],
  ["bere","Mhuka inodya zvakafa usiku","hyena","be·re","animals"],
  ["dzvinyu","Chipuka chinokwira madziro","lizard","dzvi·nyu","animals"],
  ["datya","Chipuka chinosvetuka mumvura","frog","da·tya","animals"],
  ["nyuchi","Kapuka kanogadzira uchi","bee","nyu·chi","animals"],
  ["nhunzi","Kapuka kanobhururuka kanonetsa","fly","nhu·nzi","animals"],
  ["gonye","Kapuka kanokambaira pasi","worm / caterpillar","go·nye","animals"],
  ["jongwe","Huku hono inorira mangwanani","rooster","jo·ngwe","animals"],
  ["zizi","Shiri inovhima usiku","owl","zi·zi","animals"],
  ["mhuru","Mwana wemombe","calf","mhu·ru","animals"],
  ["nyemba","Mbeu yakaita sebhinzi","cowpeas","nye·mba","food"],
  ["nzungu","Mbeu inodyiwa kana yakakangwa","groundnuts","nzu·ngu","food"],
  ["mupunga","Zviyo zvichena zvinobikwa","rice","mu·pu·nga","food"],
  ["zviyo","Mbeu dzinokuyiwa kuita upfu","grain / millet","zvi·yo","food"],
  ["upfu","Chinhu chichena chinobika sadza","mealie-meal / flour","u·pfu","food"],
  ["munyu","Chinoisa kunaka muchikafu","salt","mu·nyu","food"],
  ["uchi","Chinotapira chinogadzirwa nenyuchi","honey","u·chi","food"],
  ["mafuta","Chinoshandiswa kubika nekukanga","oil / fat","ma·fu·ta","food"],
  ["doro","Chinwiwa chinodhaka","beer","do·ro","food"],
  ["maputi","Chibage chakakangwa chinotsemuka","popcorn","ma·pu·ti","food"],
  ["matamba","Muchero mukobvu wesango","monkey orange","ma·ta·mba","food"],
  ["mango","Muchero unotapira wakatsvuka","mango","ma·ngo","food"],
  ["maungu","Muriwo mukuru unotsvuka wakaibva","pumpkin","ma·u·ngu","food"],
  ["dutu","Mhepo huru inovhuvhuta","storm / gale","du·tu","nature"],
  ["mhute","Chinhu chichena chinofukidza mangwanani","fog / mist","mhu·te","nature"],
  ["dova","Mvura diki pauswa mangwanani","dew","do·va","nature"],
  ["chando","Kutonhora kukuru kwechirimo","cold / frost","cha·ndo","nature"],
  ["bani","Nzvimbo yakati sandara isina miti","plain / grassland","ba·ni","nature"],
  ["dziva","Mvura yakamira pasi","pool / pond","dzi·va","nature"],
  ["chitsuwa","Nyika yakakomberedzwa nemvura","island","chi·tsu·wa","nature"],
  ["bako","Buri rakadzika mudombo","cave","ba·ko","nature"],
  ["jecha","Tsanga diki dzichena pamhenderekedzo","sand","je·cha","nature"],
  ["ivhu","Pasi panodyarwa zvirimwa","soil / ground","i·vhu","nature"],
  ["meso","Tunhu tuviri tunoonesa","eyes","me·so","body"],
  ["maoko","Nhengo mbiri dzokubata nadzo","hands / arms","ma·o·ko","body"],
  ["makumbo","Nhengo dzokufamba nadzo","legs","ma·ku·mbo","body"],
  ["mazino","Zvichena zviri mukanwa zvokudya","teeth","ma·zi·no","body"],
  ["rurimi","Nhengo iri mukanwa yokuravira","tongue","ru·ri·mi","body"],
  ["chiso","Divi rokumberi rwemusoro","face","chi·so","body"],
  ["huro","Nzira inopfuura chikafu","throat","hu·ro","body"],
  ["dumbu","Nhengo inochengeta chikafu","stomach / belly","du·mbu","body"],
  ["mapapu","Nhengo inoshandiswa kufema","lungs","ma·pa·pu","body"],
  ["ropa","Mvura tsvuku iri mumuviri","blood","ro·pa","body"],
  ["pfupa","Chinhu chakaoma chiri mumuviri","bone","pfu·pa","body"],
  ["chiuno","Pakati pomuviri panokombama","waist","chi·u·no","body"],
  ["gumbeze","Chinofukidza pakurara","blanket","gu·mbe·ze","household"],
  ["poto","Mudziyo wokubikira","pot","po·to","household"],
  ["banga","Chokuchekesa chakapinza","knife","ba·nga","household"],
  ["sipo","Chinoshandiswa kugeza","soap","si·po","household"],
  ["rusero","Mudziyo wokuurutsa zviyo","winnowing basket","ru·se·ro","household"],
  ["tswanda","Dengu rokuchengeta zvinhu","basket","tswa·nda","household"],
  ["chokwadi","Chinhu chisiri chenhema","truth","cho·kwa·di","values"],
  ["tsika","Maitiro akanaka anodzidziswa","customs / manners","tsi·ka","values"],
  ["ruremekedzo","Kukudza vamwe vanhu","respect","ru·re·me·ke·dzo","values"],
  ["rufaro","Kunzwa kufara mumwoyo","happiness / joy","ru·fa·ro","values"],
  ["runyararo","Mamiriro akanaka asina nyonganiso","peace","ru·nya·ra·ro","values"],
  ["tariro","Kutarisira zvakanaka mberi","hope","ta·ri·ro","values"],
  ["musika","Nzvimbo inotengeswa zvinhu","market","mu·si·ka","places"],
  ["dunhu","Chikamu chenyika","district / region","du·nhu","places"],
  ["china","Nhamba inotevera tatu","four","chi·na","numbers"],
  ["makumi","Zana rakakamurwa negumi","tens","ma·ku·mi","numbers"],
  ["zuro","Zuva rakapfuura nhasi","yesterday","zu·ro","time"],
  ["manheru","Nguva yokunenge kwava kudoka","evening","ma·nhe·ru","time"],
  ["vhiki","Nguva ina mazuva manomwe","week","vhi·ki","time"],
  ["awa","Nguva ina maminitsi makumi matanhatu","hour","a·wa","time"]
];
const ZULU_MORE=[
  ["umfowabo","Umfowabo womuntu","his / her brother","um·fo·wa·bo","family"],
  ["umalume","Umfowabo kamama","maternal uncle","u·ma·lu·me","family"],
  ["ubabamkhulu","Uyise kayihlo","grandfather","u·ba·ba·mkhu·lu","family"],
  ["umkhwenyana","Indoda yendodakazi","son-in-law","um·khwe·nya·na","family"],
  ["umakoti","Umfazi osanda kushada","bride / daughter-in-law","u·ma·ko·ti","family"],
  ["indodana","Ingane eyumfana","son","i·ndo·da·na","family"],
  ["indodakazi","Ingane eyintombazane","daughter","i·ndo·da·ka·zi","family"],
  ["umyeni","Indoda oshade nayo","husband","u·mye·ni","family"],
  ["unkosikazi","Owesifazane oshadile","wife","u·nko·si·ka·zi","family"],
  ["umzukulu","Ingane yendodana noma yendodakazi","grandchild","u·mzu·ku·lu","family"],
  ["ingwenya","Isilwane esihlala emanzini","crocodile","i·ngwe·nya","animals"],
  ["imvubu","Isilwane esikhulu somfula","hippopotamus","i·mvu·bu","animals"],
  ["indlulamithi","Isilwane esinentamo ende","giraffe","i·ndlu·la·mi·thi","animals"],
  ["idube","Isilwane elinemibala emnyama nemhlophe","zebra","i·du·be","animals"],
  ["inyathi","Isilwane esikhulu esinezimpondo","buffalo","i·nya·thi","animals"],
  ["impala","Isilwane esigijimayo ehlathini","impala","i·mpa·la","animals"],
  ["impisi","Isilwane esidla izidumbu ebusuku","hyena","i·mpi·si","animals"],
  ["ifudu","Isilwane esinegobolondo","tortoise","i·fu·du","animals"],
  ["isele","Isilwane esiqolo esihlala emanzini","frog","i·se·le","animals"],
  ["inyosi","Isinambuzane esenza uju","bee","i·nyo·si","animals"],
  ["impukane","Isinambuzane esindizayo esicasulayo","fly","i·mpu·ka·ne","animals"],
  ["iqhude","Inkukhu yeduna ekhalayo ekuseni","rooster","i·qhu·de","animals"],
  ["isikhova","Inyoni ezingela ebusuku","owl","i·si·kho·va","animals"],
  ["inkonyane","Inkomo encane","calf","i·nko·nya·ne","animals"],
  ["imamba","Inyoka enobuthi obubi","mamba","i·ma·mba","animals"],
  ["irayisi","Ukudla okumhlophe okuphekwayo","rice","i·ra·yi·si","food"],
  ["ufulawa","Impuphu yokwenza isinkwa","flour","u·fu·la·wa","food"],
  ["usawoti","Okufakwa ekudleni ukunonga","salt","u·sa·wo·ti","food"],
  ["ushukela","Okumnandi okufakwa etiyeni","sugar","u·shu·ke·la","food"],
  ["amafutha","Okusetshenziswa ukupheka","oil / fat","a·ma·fu·tha","food"],
  ["uju","Okumnandi okwenziwa zinyosi","honey","u·ju","food"],
  ["utshwala","Isiphuzo esidakayo","beer","u·tshwa·la","food"],
  ["umbila","Isitshalo esinezinhlamvu eziphuzi","maize","u·mbi·la","food"],
  ["ubhanana","Isithelo eside esiphuzi","banana","u·bha·na·na","food"],
  ["iwolintshi","Isithelo esiwumbala obomvu-mphofu","orange","i·wo·li·ntshi","food"],
  ["ithanga","Isithelo esikhulu esiphuzi","pumpkin","i·tha·nga","food"],
  ["iqanda","Okuphuma enkukhwini okudliwayo","egg","i·qa·nda","food"],
  ["isobho","Uketshezi olushisayo lokudla","soup","i·so·bho","food"],
  ["isiphepho","Umoya onamandla nesiphepho","storm","i·si·phe·pho","nature"],
  ["inkungu","Into emhlophe egubuzela ekuseni","mist / fog","i·nku·ngu","nature"],
  ["amazolo","Amanzi amancane otshanini ekuseni","dew","a·ma·zo·lo","nature"],
  ["iqhwa","Into emhlophe ebandayo ewayo","snow","i·qhwa","nature"],
  ["umhlaba","Lapho sihlala khona, inhlabathi","earth / ground","u·mhla·ba","nature"],
  ["ulwandle","Amanzi amaningi anosawoti","sea / ocean","u·lwa·ndle","nature"],
  ["ichibi","Amanzi amile emhlabeni","lake / pond","i·chi·bi","nature"],
  ["isihlabathi","Izinhlamvu ezincane olwandle","sand","i·si·hla·ba·thi","nature"],
  ["itshe","Into eqinile yedwala","stone","i·tshe","nature"],
  ["umuthi","Isihlahla noma ikhambi","tree / medicine","u·mu·thi","nature"],
  ["izinkanyezi","Lokho okukhanyayo esibhakabhakeni ebusuku","stars","i·zi·nka·nye·zi","nature"],
  ["amehlo","Izitho ezimbili zokubona","eyes","a·me·hlo","body"],
  ["izandla","Izitho ezimbili zokubamba","hands","i·za·ndla","body"],
  ["imilenze","Izitho zokuhamba","legs","i·mi·le·nze","body"],
  ["amazinyo","Okumhlophe okusemlonyeni kokuhlafuna","teeth","a·ma·zi·nyo","body"],
  ["ulimi","Isitho esisemlonyeni sokunambitha","tongue","u·li·mi","body"],
  ["ubuso","Ingxenye yangaphambili yekhanda","face","u·bu·so","body"],
  ["ikhala","Isitho sokuphefumula nokuhogela","nose","i·kha·la","body"],
  ["isisu","Isitho lapho kugcinwa khona ukudla","stomach","i·si·su","body"],
  ["igazi","Uketshezi olubomvu olusemzimbeni","blood","i·ga·zi","body"],
  ["ithambo","Into eqinile esemzimbeni","bone","i·tha·mbo","body"],
  ["unwele","Okumila ekhanda","hair","u·nwe·le","body"],
  ["umzimba","Yonke into yomuntu ngokuphelele","body","u·mzi·mba","body"],
  ["ingubo","Into yokwembesa lapho ulele","blanket","i·ngu·bo","household"],
  ["ibhokisi","Into okugcinwa kuyo izinto","box","i·bho·ki·si","household"],
  ["ummese","Into ebukhali yokusika","knife","u·mme·se","household"],
  ["insipho","Okusetshenziswa ukugeza","soap","i·nsi·pho","household"],
  ["ibhasikidi","Into yokuthwala izinto","basket","i·bha·si·ki·di","household"],
  ["isitsha","Into okudlelwa kuyo","dish / bowl","i·si·tsha","household"],
  ["isihlalo","Into yokuhlala phezu kwayo","chair","i·si·hla·lo","household"],
  ["ucango","Isivalo sokungena endlini","door","u·ca·ngo","household"],
  ["iwindi","Isikhala sokukhanya endlini","window","i·wi·ndi","household"],
  ["isibani","Into ekhanyisa ebusuku","lamp / light","i·si·ba·ni","household"],
  ["iqiniso","Into engelona amanga","truth","i·qi·ni·so","values"],
  ["inhlonipho","Ukuhlonipha abanye abantu","respect","i·nhlo·ni·pho","values"],
  ["injabulo","Umuzwa wokuthokoza","happiness / joy","i·nja·bu·lo","values"],
  ["ithemba","Ukulindela okuhle phambili","hope","i·the·mba","values"],
  ["ubuntu","Ubunye nesimo somuntu esihle","humanity / ubuntu","u·bu·ntu","values"],
  ["ukukholwa","Ukukholelwa kuNkulunkulu","faith / belief","u·ku·kho·lwa","values"],
  ["isibindi","Ukungesabi, ukuba nesibindi","courage","i·si·bi·ndi","values"],
  ["idolobha","Indawo enkulu enezakhiwo eziningi","city / town","i·do·lo·bha","places"],
  ["imakethe","Indawo lapho kuthengiselwa khona","market","i·ma·ke·the","places"],
  ["isibhedlela","Indawo lapho kwelashwa khona abagulayo","hospital","i·si·bhe·dle·la","places"],
  ["isonto","Indawo yokukhonza","church","i·so·nto","places"],
  ["umgwaqo","Indawo lapho kuhanjwa khona","road","u·mgwa·qo","places"],
  ["ihora","Isikhathi esinemizuzu engamashumi ayisithupha","hour","i·ho·ra","time"],
  ["iviki","Isikhathi esinezinsuku eziyisikhombisa","week","i·vi·ki","time"],
  ["unyaka","Isikhathi esinezinyanga eziyishumi nambili","year","u·nya·ka","time"],
  ["ekuseni","Isikhathi sokuqala sosuku","morning","e·ku·se·ni","time"],
  ["kusasa","Usuku oluzayo emva kwanamuhla","tomorrow","ku·sa·sa","time"],
  ["ishumi","Inombolo engamayunithi ayishumi","ten","i·shu·mi","numbers"]
];
/* merge: dedupe on answer, require 5 valid fields + non-empty answer */
(function(){
  const add=(arr,more)=>{const seen=new Set(arr.map(w=>w[0]));for(const w of more){
    if(Array.isArray(w)&&w.length===5&&w[0]&&w[0].trim()&&!seen.has(w[0])){arr.push(w);seen.add(w[0]);}}};
  add(LANGUAGES.Shona.words,SHONA_MORE);
  add(LANGUAGES.Zulu.words,ZULU_MORE);
})();

if(typeof window!=="undefined") window.BASE_LANGUAGES = JSON.parse(JSON.stringify(LANGUAGES));

/* ── Admin content overlay (managed by admin.html) ──
   schema: { words:{Lang:[[a,clue,en,phon,cat],...]}, hidden:{Lang:[answer,...]} } */
(function(){
  try{
    const ov=JSON.parse(localStorage.getItem("maneno_v1_customwords")||"{}");
    const adds=ov.words||{};
    for(const lng in adds){ if(!LANGUAGES[lng])continue;
      for(const word of (adds[lng]||[])){
        if(!Array.isArray(word)||word.length!==5||!word[0])continue;
        const arr=LANGUAGES[lng].words, i=arr.findIndex(x=>x[0]===word[0]);
        if(i>=0) arr[i]=word; else arr.push(word);
      }
    }
    const hid=ov.hidden||{};
    for(const lng in hid){ if(!LANGUAGES[lng])continue;
      const set=new Set(hid[lng]||[]);
      LANGUAGES[lng].words=LANGUAGES[lng].words.filter(x=>!set.has(x[0]));
    }
  }catch(e){}
})();
if(typeof window!=="undefined") window.LANGUAGES = LANGUAGES;
